name: Main workflow

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: 843282289076
  ECR_REPOSITORY: pacman-repo
  ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
jobs:
  cicd:
    name: deploy using aws eks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4            
      
    - name: Configure temporary AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
        role-session-name: github-actions-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Confirm aws credentials
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag & push docker image
      env:
          IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./docker
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Configure eks access
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name Pacman-cluster
    
    - name: EKS deployment
      run: |
        kubectl apply -f ./k8s/storage-class.yaml
        kubectl apply -f ./k8s/db-sts.yaml
        kubectl apply -f ./k8s/app-deployment.yaml
        kubectl set image deployment/pacman-app pacman=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/pacman-repo:${{ github.sha }}
        kubectl rollout status deployment pacman-app
        kubectl rollout status statefulset mongo
        kubectl get services pacman-service

     